import type { Dashboard } from "../types";

export const DASHBOARD_TEMPLATES: Dashboard[] = [
  {
    id: "template-saas-revenue",
    name: "SaaS Revenue & MRR Command Center",
    description: "Real-time subscription metrics, ARR expansion, churn velocity, and customer lifetime value.",
    category: "SaaS",
    isTemplate: true,
    tags: ["Subscriptions", "Finance", "B2B SaaS"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    generationSource: "template",
    settings: {
      density: "comfortable",
      theme: "dark",
      accent: "cyan",
      gridColumns: 12,
      showBackgroundGrid: true,
      dateRange: "Last 30 days",
    },
    widgets: [
      {
        id: "saas-mrr",
        kind: "kpi",
        title: "Monthly Recurring Revenue",
        subtitle: "Net new subscriptions",
        metric: "$142,850",
        change: "+14.2%",
        changePeriod: "vs last month",
        changeType: "increase",
        size: "sm",
        accent: "cyan",
        data: [98, 105, 112, 119, 128, 136, 143],
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "saas-arr",
        kind: "kpi",
        title: "Annual Run Rate",
        subtitle: "Projected 12m trajectory",
        metric: "$1.71M",
        change: "+22.8%",
        changePeriod: "vs previous quarter",
        changeType: "increase",
        size: "sm",
        accent: "blue",
        data: [1.1, 1.2, 1.35, 1.48, 1.58, 1.71],
        labels: ["Q1", "Q2", "Q3", "Q4", "Q1", "Q2"],
      },
      {
        id: "saas-churn",
        kind: "kpi",
        title: "Logo Churn Rate",
        subtitle: "Monthly subscriber attrition",
        metric: "1.24%",
        change: "-0.3%",
        changePeriod: "lower than benchmark",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [2.1, 1.9, 1.8, 1.5, 1.4, 1.24],
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
      },
      {
        id: "saas-nrr",
        kind: "kpi",
        title: "Net Revenue Retention",
        subtitle: "Expansion minus contraction",
        metric: "118.4%",
        change: "+4.1%",
        changePeriod: "cohort average",
        changeType: "increase",
        size: "sm",
        accent: "violet",
        data: [106, 109, 112, 115, 117, 118.4],
        labels: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "saas-growth-trend",
        kind: "line",
        title: "MRR Growth & New Bookings",
        subtitle: "Monthly breakdown of new enterprise vs self-serve revenue",
        metric: "$28.4K New ARR",
        change: "+18.6%",
        changeType: "increase",
        size: "lg",
        accent: "cyan",
        data: [35, 42, 58, 64, 76, 85, 92, 105, 118, 142],
        labels: ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "saas-plan-mix",
        kind: "donut",
        title: "Subscription Tier Mix",
        subtitle: "Revenue split across customer tiers",
        metric: "1,420 Subscriptions",
        change: "Enterprise +32%",
        changeType: "increase",
        size: "md",
        accent: "blue",
        data: [52, 33, 15],
        labels: ["Enterprise", "Scale Pro", "Starter"],
      },
      {
        id: "saas-top-accounts",
        kind: "table",
        title: "Top Expansion Accounts",
        subtitle: "High ARR enterprise customers with upsell probability",
        metric: "18 Accounts",
        change: "+5 closed",
        changeType: "increase",
        size: "lg",
        accent: "cyan",
        data: [96, 88, 82, 74, 68],
        labels: ["Vercel Scale", "Linear Corp", "Raycast Labs", "Retool Inc", "Figma Design"],
        config: {
          tableRows: [
            { id: "1", name: "Vercel Enterprise", category: "Annual Plan", value: "$48,000", change: "+120 seats", status: "active", progress: 95 },
            { id: "2", name: "Linear Operations", category: "Annual Plan", value: "$36,400", change: "+85 seats", status: "active", progress: 88 },
            { id: "3", name: "Raycast Ecosystem", category: "Monthly", value: "$24,200", change: "+40 seats", status: "active", progress: 78 },
            { id: "4", name: "Retool Workflow Hub", category: "Annual Plan", value: "$19,800", change: "+25 seats", status: "pending", progress: 65 },
          ],
        },
      },
      {
        id: "saas-conversion-progress",
        kind: "progress",
        title: "Quarterly Sales Target",
        subtitle: "Q2 Closed ARR vs $500K Goal",
        metric: "$420K / $500K",
        change: "84% Achieved",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [84],
        config: {
          target: 500000,
          max: 500000,
        },
      },
      {
        id: "saas-system-health",
        kind: "gauge",
        title: "Customer Health Score",
        subtitle: "Platform engagement & NPS composite",
        metric: "92 / 100",
        change: "+4 pts vs Q1",
        changeType: "increase",
        size: "sm",
        accent: "cyan",
        data: [92],
        config: {
          target: 90,
          max: 100,
        },
      },
    ],
  },
  {
    id: "template-ecommerce-growth",
    name: "E-Commerce & Retail Performance",
    description: "Store conversion rate, average order value, cart abandonment, and product category velocity.",
    category: "E-Commerce",
    isTemplate: true,
    tags: ["Retail", "D2C", "Shopify"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    generationSource: "template",
    settings: {
      density: "comfortable",
      theme: "dark",
      accent: "emerald",
      gridColumns: 12,
      showBackgroundGrid: true,
      dateRange: "Last 7 days",
    },
    widgets: [
      {
        id: "ecom-gmv",
        kind: "kpi",
        title: "Gross Merchandise Value",
        subtitle: "Total retail checkout volume",
        metric: "$384,920",
        change: "+19.4%",
        changePeriod: "vs prior week",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [42, 48, 55, 62, 71, 79, 88],
        labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      },
      {
        id: "ecom-aov",
        kind: "kpi",
        title: "Average Order Value",
        subtitle: "Basket size per transaction",
        metric: "$114.50",
        change: "+$8.20",
        changePeriod: "with bundle offers",
        changeType: "increase",
        size: "sm",
        accent: "cyan",
        data: [95, 98, 102, 106, 110, 114.5],
        labels: ["W1", "W2", "W3", "W4", "W5", "W6"],
      },
      {
        id: "ecom-conversion",
        kind: "kpi",
        title: "Store Conversion Rate",
        subtitle: "Visitor to completed order",
        metric: "3.85%",
        change: "+0.45%",
        changePeriod: "top 10% benchmark",
        changeType: "increase",
        size: "sm",
        accent: "amber",
        data: [3.1, 3.2, 3.4, 3.6, 3.75, 3.85],
        labels: ["W1", "W2", "W3", "W4", "W5", "W6"],
      },
      {
        id: "ecom-orders",
        kind: "kpi",
        title: "Fulfillment Velocity",
        subtitle: "Average dispatch latency",
        metric: "4.2 hrs",
        change: "-1.8 hrs",
        changePeriod: "same-day ready",
        changeType: "increase",
        size: "sm",
        accent: "blue",
        data: [8.5, 7.2, 6.1, 5.4, 4.8, 4.2],
        labels: ["W1", "W2", "W3", "W4", "W5", "W6"],
      },
      {
        id: "ecom-revenue-bars",
        kind: "bar",
        title: "Daily Revenue vs Target",
        subtitle: "Performance across major shopping channels",
        metric: "$54.8K Peak Day",
        change: "+28%",
        changeType: "increase",
        size: "md",
        accent: "emerald",
        data: [42, 58, 64, 78, 86, 94, 72],
        labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      },
      {
        id: "ecom-traffic-channels",
        kind: "donut",
        title: "Acquisition Channel Mix",
        subtitle: "Order volume by acquisition source",
        metric: "3,360 Orders",
        change: "Organic 44%",
        changeType: "increase",
        size: "md",
        accent: "violet",
        data: [44, 28, 18, 10],
        labels: ["Direct / Organic", "Meta Ads", "Google Shopping", "Affiliates"],
      },
      {
        id: "ecom-top-skus",
        kind: "table",
        title: "Bestselling Products",
        subtitle: "Inventory velocity and margin breakdown",
        metric: "Top 4 SKUs",
        change: "+12% gross margin",
        changeType: "increase",
        size: "lg",
        accent: "emerald",
        data: [94, 88, 76, 65],
        labels: ["Studio Wireless Pro", "Ergonomic Desk Mat", "USB-C Travel Dock", "Mechanical Keypad"],
        config: {
          tableRows: [
            { id: "1", name: "Studio Wireless Pro ANC", category: "Audio", value: "$88,400", change: "420 units", status: "active", progress: 92 },
            { id: "2", name: "Ergonomic Desk Mat XL", category: "Workspace", value: "$34,200", change: "680 units", status: "active", progress: 84 },
            { id: "3", name: "USB-C Multiport Dock", category: "Hardware", value: "$28,900", change: "310 units", status: "active", progress: 74 },
            { id: "4", name: "Precision Dial Keypad", category: "Accessories", value: "$19,600", change: "195 units", status: "pending", progress: 58 },
          ],
        },
      },
      {
        id: "ecom-cart-rate",
        kind: "gauge",
        title: "Checkout Funnel Completion",
        subtitle: "Cart to completed purchase ratio",
        metric: "68.2%",
        change: "+5.4%",
        changeType: "increase",
        size: "sm",
        accent: "amber",
        data: [68],
        config: {
          target: 70,
          max: 100,
        },
      },
    ],
  },
  {
    id: "template-devops-infrastructure",
    name: "Cloud Infrastructure & DevOps Health",
    description: "API latencies, cluster CPU loads, error budgets, deployments, and uptime monitoring.",
    category: "DevOps",
    isTemplate: true,
    tags: ["Kubernetes", "SRE", "Infrastructure"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    generationSource: "template",
    settings: {
      density: "compact",
      theme: "dark",
      accent: "rose",
      gridColumns: 12,
      showBackgroundGrid: true,
      dateRange: "Real-time stream",
    },
    widgets: [
      {
        id: "devops-p99",
        kind: "kpi",
        title: "API P99 Latency",
        subtitle: "Global edge gateway",
        metric: "38 ms",
        change: "-6 ms",
        changePeriod: "within 50ms SLA",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [58, 52, 46, 44, 41, 38],
        labels: ["12:00", "12:10", "12:20", "12:30", "12:40", "12:50"],
      },
      {
        id: "devops-uptime",
        kind: "kpi",
        title: "Global Service Uptime",
        subtitle: "Last 90 days rolling",
        metric: "99.994%",
        change: "0 incidents",
        changePeriod: "all regions green",
        changeType: "neutral",
        size: "sm",
        accent: "cyan",
        data: [99.99, 99.99, 99.99, 99.99, 99.994],
        labels: ["Jan", "Feb", "Mar", "Apr", "May"],
      },
      {
        id: "devops-error-rate",
        kind: "kpi",
        title: "HTTP 5xx Error Rate",
        subtitle: "Edge ingress traffic",
        metric: "0.012%",
        change: "-0.008%",
        changePeriod: "healthy baseline",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [0.04, 0.03, 0.025, 0.018, 0.012],
        labels: ["12:00", "12:15", "12:30", "12:45", "13:00"],
      },
      {
        id: "devops-cluster-cpu",
        kind: "kpi",
        title: "Cluster Compute Utilization",
        subtitle: "64 Node Kube pool",
        metric: "58.4%",
        change: "+3.2%",
        changePeriod: "headroom 41.6%",
        changeType: "neutral",
        size: "sm",
        accent: "violet",
        data: [45, 52, 58, 54, 61, 58.4],
        labels: ["T-5h", "T-4h", "T-3h", "T-2h", "T-1h", "Now"],
      },
      {
        id: "devops-traffic-area",
        kind: "area",
        title: "Edge Ingress Requests / Sec",
        subtitle: "Global traffic distribution across North America, Europe, and Asia Pacific",
        metric: "48.2K req/sec",
        change: "+12.4%",
        changeType: "increase",
        size: "lg",
        accent: "rose",
        data: [28, 34, 42, 51, 62, 74, 88, 79, 65, 82],
        labels: ["00:00", "02:00", "04:00", "06:00", "08:00", "10:00", "12:00", "14:00", "16:00", "18:00"],
      },
      {
        id: "devops-status-widget",
        kind: "status",
        title: "Core Service Availability",
        subtitle: "Microservices health & heartbeat status",
        metric: "12 / 12 Healthy",
        change: "100% operational",
        changeType: "increase",
        size: "md",
        accent: "emerald",
        data: [100, 100, 100, 100, 100],
        config: {
          statusType: "healthy",
        },
      },
      {
        id: "devops-activity-feed",
        kind: "activity",
        title: "Recent Deployments & Events",
        subtitle: "Automated CI/CD pipeline triggers and rollouts",
        metric: "6 Deployments today",
        change: "Zero rollbacks",
        changeType: "increase",
        size: "lg",
        accent: "cyan",
        data: [100, 100, 100],
        config: {
          activityItems: [
            { id: "1", user: "alex.dev", action: "deployed release", target: "api-v2.18.4 to prod-us-east", time: "8m ago", status: "success" },
            { id: "2", user: "system", action: "autoscaled pods", target: "auth-service (+12 pods)", time: "24m ago", status: "info" },
            { id: "3", user: "ci-bot", action: "completed test run", target: "billing-worker (1,480 tests)", time: "46m ago", status: "success" },
            { id: "4", user: "sarah.sre", action: "rotated secrets", target: "database-cluster-primary", time: "2h ago", status: "info" },
          ],
        },
      },
      {
        id: "devops-error-gauge",
        kind: "gauge",
        title: "Error Budget Remaining",
        subtitle: "Monthly 99.95% SLO threshold",
        metric: "94.2%",
        change: "Budget healthy",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [94],
        config: {
          target: 90,
          max: 100,
        },
      },
    ],
  },
  {
    id: "template-marketing-funnel",
    name: "Marketing Acquisition & Pipeline Funnel",
    description: "Paid ROAS, blended CAC, MQL to SQL conversion, and campaign attribution breakdown.",
    category: "Marketing",
    isTemplate: true,
    tags: ["Growth", "Advertising", "Lead Gen"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    generationSource: "template",
    settings: {
      density: "comfortable",
      theme: "dark",
      accent: "violet",
      gridColumns: 12,
      showBackgroundGrid: true,
      dateRange: "Quarter to Date",
    },
    widgets: [
      {
        id: "mkt-pipeline",
        kind: "kpi",
        title: "Qualified Pipeline Created",
        subtitle: "Sales-accepted opportunities",
        metric: "$892,400",
        change: "+26.4%",
        changePeriod: "vs target pace",
        changeType: "increase",
        size: "sm",
        accent: "violet",
        data: [120, 180, 260, 420, 610, 780, 892],
        labels: ["W1", "W2", "W3", "W4", "W5", "W6", "W7"],
      },
      {
        id: "mkt-cac",
        kind: "kpi",
        title: "Blended Customer CAC",
        subtitle: "Fully loaded acquisition cost",
        metric: "$340",
        change: "-$48",
        changePeriod: "improved efficiency",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [420, 395, 380, 365, 350, 340],
        labels: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "mkt-roas",
        kind: "kpi",
        title: "Paid Campaign ROAS",
        subtitle: "Direct attribution return",
        metric: "4.82x",
        change: "+0.6x",
        changePeriod: "above 4.0x target",
        changeType: "increase",
        size: "sm",
        accent: "cyan",
        data: [3.4, 3.8, 4.1, 4.3, 4.6, 4.82],
        labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
      },
      {
        id: "mkt-leads",
        kind: "kpi",
        title: "Demo Request Volume",
        subtitle: "High intent inbound leads",
        metric: "1,280",
        change: "+34%",
        changePeriod: "conversion rate 18%",
        changeType: "increase",
        size: "sm",
        accent: "amber",
        data: [680, 790, 920, 1050, 1180, 1280],
        labels: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
      },
      {
        id: "mkt-funnel-bar",
        kind: "bar",
        title: "Stage Conversion Funnel",
        subtitle: "Visitor -> Signup -> Activation -> Paid Customer",
        metric: "4,820 Total Inbound",
        change: "+16%",
        changeType: "increase",
        size: "md",
        accent: "violet",
        data: [100, 68, 42, 28, 14],
        labels: ["Visitors", "Signups", "Activations", "MQLs", "Customers"],
      },
      {
        id: "mkt-spend-mix",
        kind: "donut",
        title: "Marketing Budget Allocation",
        subtitle: "Channel expenditure breakdown",
        metric: "$140K Spent",
        change: "Paid Search 38%",
        changeType: "increase",
        size: "md",
        accent: "indigo",
        data: [38, 26, 22, 14],
        labels: ["Google Search", "LinkedIn Ads", "Content & SEO", "Events"],
      },
      {
        id: "mkt-campaign-table",
        kind: "table",
        title: "Top Performing Campaigns",
        subtitle: "Lead volume, CPL, and closed-won pipeline",
        metric: "5 Campaigns",
        change: "+$320K pipeline",
        changeType: "increase",
        size: "lg",
        accent: "violet",
        data: [92, 84, 76, 68],
        labels: ["Enterprise Demo 2026", "Developer Tool Launch", "Security Whitepaper", "Startup Free Tier"],
        config: {
          tableRows: [
            { id: "1", name: "Enterprise Demo Search", category: "Google Ads", value: "$380K Pipeline", change: "$142 CPL", status: "active", progress: 92 },
            { id: "2", name: "Developer Launchpad", category: "LinkedIn", value: "$260K Pipeline", change: "$88 CPL", status: "active", progress: 84 },
            { id: "3", name: "SOC2 Compliance E-book", category: "Content", value: "$185K Pipeline", change: "$45 CPL", status: "active", progress: 76 },
            { id: "4", name: "Product Comparison Page", category: "SEO", value: "$140K Pipeline", change: "$28 CPL", status: "completed", progress: 68 },
          ],
        },
      },
    ],
  },
  {
    id: "template-product-analytics",
    name: "Product Telemetry & User Retention",
    description: "Daily active users, cohort retention curve, feature adoption rate, and session durations.",
    category: "Product",
    isTemplate: true,
    tags: ["Product", "Retention", "Telemetry"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    generationSource: "template",
    settings: {
      density: "comfortable",
      theme: "dark",
      accent: "indigo",
      gridColumns: 12,
      showBackgroundGrid: true,
      dateRange: "Last 30 days",
    },
    widgets: [
      {
        id: "prod-dau",
        kind: "kpi",
        title: "Daily Active Users",
        subtitle: "Unique authenticated sessions",
        metric: "64,280",
        change: "+16.8%",
        changePeriod: "DAU/MAU 42%",
        changeType: "increase",
        size: "sm",
        accent: "indigo",
        data: [42, 48, 51, 56, 59, 64.2],
        labels: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "prod-retention",
        kind: "kpi",
        title: "D30 Cohort Retention",
        subtitle: "Monthly recurring user retention",
        metric: "52.4%",
        change: "+4.2%",
        changePeriod: "top quartile benchmark",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [44, 46, 48, 50, 52.4],
        labels: ["M1", "M2", "M3", "M4", "M5"],
      },
      {
        id: "prod-session-time",
        kind: "kpi",
        title: "Avg Session Duration",
        subtitle: "Time on active dashboard",
        metric: "18m 42s",
        change: "+2m 14s",
        changePeriod: "engagement up",
        changeType: "increase",
        size: "sm",
        accent: "cyan",
        data: [12, 14, 15, 16, 17, 18.7],
        labels: ["W1", "W2", "W3", "W4", "W5", "W6"],
      },
      {
        id: "prod-activation",
        kind: "kpi",
        title: "New User Activation",
        subtitle: "First dashboard created in 24h",
        metric: "74.8%",
        change: "+8.1%",
        changePeriod: "improved onboarding",
        changeType: "increase",
        size: "sm",
        accent: "blue",
        data: [58, 62, 66, 71, 74.8],
        labels: ["Nov", "Dec", "Jan", "Feb", "Mar"],
      },
      {
        id: "prod-dau-trend",
        kind: "line",
        title: "Active Users Trajectory (DAU / WAU)",
        subtitle: "Daily engagement spikes and weekly active baseline",
        metric: "182K Monthly Active Users",
        change: "+24%",
        changeType: "increase",
        size: "lg",
        accent: "indigo",
        data: [48, 55, 62, 74, 88, 96, 112, 134, 158, 182],
        labels: ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "prod-feature-adoption",
        kind: "bar",
        title: "Feature Usage Adoption",
        subtitle: "Adoption percentage across primary studio tools",
        metric: "88% AI Builder Usage",
        change: "+32%",
        changeType: "increase",
        size: "md",
        accent: "cyan",
        data: [88, 76, 68, 54, 42],
        labels: ["AI Generator", "Inspector Edits", "Custom Data", "Team Sharing", "API Sync"],
      },
    ],
  },
  {
    id: "template-finance-cashflow",
    name: "Financial Performance & Cash Flow",
    description: "Operating margins, runway burn rate, gross profit, and enterprise contract receivables.",
    category: "Finance",
    isTemplate: true,
    tags: ["Finance", "Cash Flow", "Treasury"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    generationSource: "template",
    settings: {
      density: "comfortable",
      theme: "dark",
      accent: "amber",
      gridColumns: 12,
      showBackgroundGrid: true,
      dateRange: "Current Fiscal Year",
    },
    widgets: [
      {
        id: "fin-cash-balance",
        kind: "kpi",
        title: "Total Treasury Balance",
        subtitle: "Cash & yield equivalents",
        metric: "$4.82M",
        change: "+$320K",
        changePeriod: "runway 32 months",
        changeType: "increase",
        size: "sm",
        accent: "amber",
        data: [3.8, 4.0, 4.2, 4.5, 4.7, 4.82],
        labels: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "fin-gross-margin",
        kind: "kpi",
        title: "Gross Profit Margin",
        subtitle: "After cloud hosting & support",
        metric: "84.2%",
        change: "+2.6%",
        changePeriod: "cloud optimization",
        changeType: "increase",
        size: "sm",
        accent: "emerald",
        data: [78, 80, 81, 82.5, 83.5, 84.2],
        labels: ["Q1", "Q2", "Q3", "Q4", "Q1", "Q2"],
      },
      {
        id: "fin-net-burn",
        kind: "kpi",
        title: "Monthly Net Burn",
        subtitle: "Operational expenses minus revenue",
        metric: "$42.5K",
        change: "-$18K",
        changePeriod: "heading to breakeven",
        changeType: "increase",
        size: "sm",
        accent: "cyan",
        data: [95, 82, 71, 60, 52, 42.5],
        labels: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "fin-ebitda",
        kind: "kpi",
        title: "Operating Cash Flow",
        subtitle: "Trailing 12 month aggregate",
        metric: "+$128K",
        change: "+$85K",
        changePeriod: "positive trajectory",
        changeType: "increase",
        size: "sm",
        accent: "blue",
        data: [-40, -15, 10, 45, 85, 128],
        labels: ["Q1", "Q2", "Q3", "Q4", "Q1", "Q2"],
      },
      {
        id: "fin-revenue-forecast",
        kind: "area",
        title: "Revenue & Expense Trajectory",
        subtitle: "Monthly cash inflows vs operating expenditures",
        metric: "$168K Cash Flow / Mo",
        change: "+22%",
        changeType: "increase",
        size: "lg",
        accent: "amber",
        data: [42, 55, 68, 84, 98, 115, 134, 148, 168],
        labels: ["Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
      },
      {
        id: "fin-expense-mix",
        kind: "donut",
        title: "OpEx Department Breakdown",
        subtitle: "Distribution of monthly expenditures",
        metric: "$182K Total OpEx",
        change: "R&D 54%",
        changeType: "neutral",
        size: "md",
        accent: "rose",
        data: [54, 26, 12, 8],
        labels: ["R&D & Engineering", "Sales & Marketing", "Cloud Infrastructure", "G&A / Legal"],
      },
    ],
  },
];
